import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Theme-aware neutrals (mapped in globals.css)
        midnight: {
          50: 'rgb(var(--color-midnight-50) / <alpha-value>)',
          100: 'rgb(var(--color-midnight-100) / <alpha-value>)',
          200: 'rgb(var(--color-midnight-200) / <alpha-value>)',
          300: 'rgb(var(--color-midnight-300) / <alpha-value>)',
          400: 'rgb(var(--color-midnight-400) / <alpha-value>)',
          500: 'rgb(var(--color-midnight-500) / <alpha-value>)',
          600: 'rgb(var(--color-midnight-600) / <alpha-value>)',
          700: 'rgb(var(--color-midnight-700) / <alpha-value>)',
          800: 'rgb(var(--color-midnight-800) / <alpha-value>)',
          900: 'rgb(var(--color-midnight-900) / <alpha-value>)',
          950: 'rgb(var(--color-midnight-950) / <alpha-value>)',
        },
        surface: {
          50: 'rgb(var(--color-surface-50) / <alpha-value>)',
          100: 'rgb(var(--color-surface-100) / <alpha-value>)',
          200: 'rgb(var(--color-surface-200) / <alpha-value>)',
          300: 'rgb(var(--color-surface-300) / <alpha-value>)',
          400: 'rgb(var(--color-surface-400) / <alpha-value>)',
          500: 'rgb(var(--color-surface-500) / <alpha-value>)',
          600: 'rgb(var(--color-surface-600) / <alpha-value>)',
          700: 'rgb(var(--color-surface-700) / <alpha-value>)',
          800: 'rgb(var(--color-surface-800) / <alpha-value>)',
          900: 'rgb(var(--color-surface-900) / <alpha-value>)',
          950: 'rgb(var(--color-surface-950) / <alpha-value>)',
        },
        // Primary steel-blue spectrum
        electric: {
          50: 'rgb(var(--color-primary-50) / <alpha-value>)',
          100: 'rgb(var(--color-primary-100) / <alpha-value>)',
          200: 'rgb(var(--color-primary-200) / <alpha-value>)',
          300: 'rgb(var(--color-primary-300) / <alpha-value>)',
          400: 'rgb(var(--color-primary-400) / <alpha-value>)',
          500: 'rgb(var(--color-primary-500) / <alpha-value>)',
          600: 'rgb(var(--color-primary-600) / <alpha-value>)',
          700: 'rgb(var(--color-primary-700) / <alpha-value>)',
          800: 'rgb(var(--color-primary-800) / <alpha-value>)',
          900: 'rgb(var(--color-primary-900) / <alpha-value>)',
        },
        profit: {
          50: 'rgb(var(--color-success-50) / <alpha-value>)',
          100: 'rgb(var(--color-success-100) / <alpha-value>)',
          200: 'rgb(var(--color-success-200) / <alpha-value>)',
          300: 'rgb(var(--color-success-300) / <alpha-value>)',
          400: 'rgb(var(--color-success-400) / <alpha-value>)',
          500: 'rgb(var(--color-success-500) / <alpha-value>)',
          600: 'rgb(var(--color-success-600) / <alpha-value>)',
          700: 'rgb(var(--color-success-700) / <alpha-value>)',
          800: 'rgb(var(--color-success-800) / <alpha-value>)',
          900: 'rgb(var(--color-success-900) / <alpha-value>)',
        },
        loss: {
          50: 'rgb(var(--color-danger-50) / <alpha-value>)',
          100: 'rgb(var(--color-danger-100) / <alpha-value>)',
          200: 'rgb(var(--color-danger-200) / <alpha-value>)',
          300: 'rgb(var(--color-danger-300) / <alpha-value>)',
          400: 'rgb(var(--color-danger-400) / <alpha-value>)',
          500: 'rgb(var(--color-danger-500) / <alpha-value>)',
          600: 'rgb(var(--color-danger-600) / <alpha-value>)',
          700: 'rgb(var(--color-danger-700) / <alpha-value>)',
          800: 'rgb(var(--color-danger-800) / <alpha-value>)',
          900: 'rgb(var(--color-danger-900) / <alpha-value>)',
        },
        chart: {
          blue: 'rgb(var(--color-chart-blue) / <alpha-value>)',
          cyan: 'rgb(var(--color-chart-cyan) / <alpha-value>)',
          teal: 'rgb(var(--color-chart-teal) / <alpha-value>)',
          green: 'rgb(var(--color-chart-green) / <alpha-value>)',
          yellow: 'rgb(var(--color-chart-yellow) / <alpha-value>)',
          orange: 'rgb(var(--color-chart-orange) / <alpha-value>)',
          red: 'rgb(var(--color-chart-red) / <alpha-value>)',
          purple: 'rgb(var(--color-chart-purple) / <alpha-value>)',
        },
        canvas: 'rgb(var(--color-canvas) / <alpha-value>)',
        border: 'rgb(var(--color-border) / <alpha-value>)',
        ink: 'rgb(var(--color-ink) / <alpha-value>)',
        muted: 'rgb(var(--color-muted) / <alpha-value>)',
        primary: 'rgb(var(--color-primary-600) / <alpha-value>)',
        'primary-soft': 'rgb(var(--color-primary-soft) / <alpha-value>)',
        success: 'rgb(var(--color-success-600) / <alpha-value>)',
        warning: 'rgb(var(--color-warning-600) / <alpha-value>)',
        danger: 'rgb(var(--color-danger-600) / <alpha-value>)',
        info: 'rgb(var(--color-info-600) / <alpha-value>)',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-mono)', 'ui-monospace', 'SFMono-Regular', 'monospace'],
        display: ['var(--font-sans)', 'system-ui', 'sans-serif'],
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-hero': 'linear-gradient(135deg, rgba(230, 236, 245, 0.8) 0%, rgba(237, 242, 255, 0.6) 50%, rgba(241, 246, 255, 0.8) 100%)',
        'gradient-hero-dark': 'linear-gradient(135deg, rgba(17, 23, 35, 0.9) 0%, rgba(26, 38, 64, 0.75) 50%, rgba(19, 32, 51, 0.9) 100%)',
        'mesh-soft': 'radial-gradient(at 20% 30%, rgba(31, 58, 95, 0.08) 0px, transparent 50%), radial-gradient(at 80% 60%, rgba(61, 90, 128, 0.06) 0px, transparent 50%)',
        'mesh-soft-dark': 'radial-gradient(at 20% 30%, rgba(143, 179, 255, 0.08) 0px, transparent 50%), radial-gradient(at 80% 60%, rgba(143, 179, 255, 0.04) 0px, transparent 50%)',
        'glass-gradient': 'linear-gradient(135deg, rgba(255, 255, 255, 0.16) 0%, rgba(255, 255, 255, 0.04) 100%)',
      },
      boxShadow: {
        'glass': '0 12px 30px rgba(15, 23, 42, 0.08)',
        'glass-lg': '0 20px 45px rgba(15, 23, 42, 0.12)',
        'elevation-1': '0 1px 2px rgba(15, 23, 42, 0.06)',
        'elevation-2': '0 4px 10px rgba(15, 23, 42, 0.08)',
        'elevation-3': '0 10px 22px rgba(15, 23, 42, 0.12)',
        'inner-glow': 'inset 0 1px 0 rgba(255, 255, 255, 0.5)',
      },
      borderRadius: {
        '4xl': '2rem',
        '5xl': '2.5rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.32s var(--easing-standard)',
        'fade-in-up': 'fadeInUp 0.32s var(--easing-standard)',
        'fade-in-down': 'fadeInDown 0.32s var(--easing-standard)',
        'slide-in-right': 'slideInRight 0.28s var(--easing-standard)',
        'slide-in-left': 'slideInLeft 0.28s var(--easing-standard)',
        'scale-in': 'scaleIn 0.2s var(--easing-standard)',
        'shimmer': 'shimmer 1.2s linear infinite',
        'reveal-stagger': 'revealStagger 0.28s var(--easing-standard)',
        'chart-line': 'chartLine 0.8s var(--easing-standard)',
        'chart-bar': 'chartBar 0.8s var(--easing-standard)',
        'count-up': 'countUp 0.6s var(--easing-standard)',
        'pulse-soft': 'pulseSoft 2.2s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        fadeInUp: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        fadeInDown: {
          '0%': { opacity: '0', transform: 'translateY(-10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideInRight: {
          '0%': { opacity: '0', transform: 'translateX(-10px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        slideInLeft: {
          '0%': { opacity: '0', transform: 'translateX(10px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          '0%': { opacity: '0', transform: 'scale(0.95)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        shimmer: {
          '0%': { backgroundPosition: '-200% 0' },
          '100%': { backgroundPosition: '200% 0' },
        },
        revealStagger: {
          '0%': { opacity: '0', transform: 'translateY(6px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        chartLine: {
          '0%': { strokeDashoffset: '1000' },
          '100%': { strokeDashoffset: '0' },
        },
        chartBar: {
          '0%': { transform: 'scaleY(0)' },
          '100%': { transform: 'scaleY(1)' },
        },
        countUp: {
          '0%': { transform: 'translateY(6px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '0.6' },
          '50%': { opacity: '1' },
        },
      },
      transitionTimingFunction: {
        'smooth': 'cubic-bezier(0.2, 0.8, 0.2, 1)',
        'exit': 'cubic-bezier(0.4, 0, 1, 1)',
      },
      backdropBlur: {
        xs: '2px',
        '3xl': '64px',
      },
    },
  },
  plugins: [],
}
export default config
